-- ============================================================================
-- Basements — Engelleme (blocks) + Şikayet (reports)
-- Supabase SQL Editor'da BIR KEZ calistir. Idempotent (tekrar guvenli).
-- Guvenlik modeli digerleriyle ayni: RLS acik, policy yok -> erisim yalniz
-- service-role (uygulamanin API route'lari) + getMe() app-seviyesi auth ile.
-- SQL calismadan once kod DEFANSIF: tablolar yoksa engelle/sikayet sessizce
-- devre disidir (buton hata verir ama sayfa/feed kirilmaz).
-- ============================================================================

-- Engellemeler: blocker_id, blocked_id'yi engelledi. Iki yonlu etki uygulamada:
-- ya A B'yi ya da B A'yi engellediyse -> birbirlerinin icerigini/DM'ini goremezler.
create table if not exists public.blocks (
  id         bigint generated by default as identity primary key,
  blocker_id bigint not null references public.users(id) on delete cascade,
  blocked_id bigint not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (blocker_id, blocked_id),
  check (blocker_id <> blocked_id)
);
alter table public.blocks enable row level security;
create index if not exists idx_blocks_blocker on public.blocks (blocker_id);
create index if not exists idx_blocks_blocked on public.blocks (blocked_id);

-- Sikayetler: icerik/kullanici moderasyon kuyrugu. target_type + target_id
-- polimorfik (post=quick_facts.id, comment=comments.id, user=users.id,
-- article=user_articles.id, article_comment=article_comments.id). status ile
-- yonetici islem gorur.
create table if not exists public.reports (
  id          bigint generated by default as identity primary key,
  reporter_id bigint not null references public.users(id) on delete cascade,
  target_type text   not null check (target_type in ('post','comment','user','article','article_comment')),
  target_id   bigint not null,
  reason      text   not null,
  note        text,
  status      text   not null default 'open' check (status in ('open','reviewed','dismissed')),
  created_at  timestamptz not null default now()
);
alter table public.reports enable row level security;
-- Mevcut kurulumlarda (tablo zaten varsa) target_type CHECK'ini guncelle.
alter table public.reports drop constraint if exists reports_target_type_check;
alter table public.reports add constraint reports_target_type_check
  check (target_type in ('post','comment','user','article','article_comment'));
create index if not exists idx_reports_open     on public.reports (status, created_at desc);
create index if not exists idx_reports_reporter on public.reports (reporter_id, created_at desc);
-- Ayni kisi ayni hedefi bir kez sikayet etsin (spam onleme).
create unique index if not exists uq_reports_once on public.reports (reporter_id, target_type, target_id);

-- ============================================================================
-- BITTI. Calisinca: profil "..." menusunde Engelle/Sikayet aktif olur; engelli
-- kullanicilar feed/arama/DM/yorum/takip'te birbirini goremez/etkilesemez.
-- ============================================================================
