-- ============================================================================
-- Basements — Kullanici Makaleleri (kullanicilar kendi makalelerini yazip yayinlar)
-- Supabase SQL Editor'da BIR KEZ calistir. Idempotent (tekrar guvenli).
-- Mevcut guvenlik modeline uyar: RLS acik, policy yok -> erisim yalniz
-- service-role (uygulamanin API route'lari) + getMe() app-seviyesi auth ile.
-- ============================================================================

-- 1) Admin bayragi: makale onay kuyrugunu (pending -> approved) kim onaylayacak.
--    Varsayilan false; asagidaki UPDATE ile kendini admin yap.
alter table public.users add column if not exists is_admin boolean not null default false;

-- 2) Kullanici makaleleri.
--    doc: blok dizisi (jsonb) -> [{type:'text',html}, {type:'image',url}, {type:'embed',...}]
--    sources: Kaynakca (jsonb) -> [{title,authors,year,source,url}]
--    status: pending (incelemede) | approved (yayinda) | rejected (reddedildi)
create table if not exists public.user_articles (
  id            bigint generated by default as identity primary key,
  user_id       bigint not null references public.users(id) on delete cascade,
  slug          text   not null unique,
  title         text   not null,
  summary       text   not null default '',
  cover_url     text,
  category      text,
  doc           jsonb  not null default '[]'::jsonb,
  sources       jsonb  not null default '[]'::jsonb,
  status        text   not null default 'pending' check (status in ('pending','approved','rejected')),
  reject_reason text,
  view_count    bigint not null default 0,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  published_at  timestamptz
);
alter table public.user_articles enable row level security;

-- Yayindaki makaleler (keşfet/feed icin), kullanicinin kendi makaleleri (profil/editor),
-- ve onay kuyrugu (admin) sorgulari icin indeksler.
create index if not exists idx_user_articles_status_published
  on public.user_articles (status, published_at desc);
create index if not exists idx_user_articles_user_created
  on public.user_articles (user_id, created_at desc);
-- slug zaten unique constraint ile indekslidir.

-- ============================================================================
-- KENDINI ADMIN YAP — asagidaki satirdaki 'KULLANICI_ADIN' kismini kendi
-- kullanici adinla degistirip calistir (yorum isaretini kaldir):
--
--   update public.users set is_admin = true where username = 'KULLANICI_ADIN';
--
-- Alternatif: Netlify ortam degiskeni ADMIN_USERNAMES="kullanici1,kullanici2"
-- ayarlarsan SQL'siz de admin tanimlanabilir (kod ikisini de kabul eder).
-- ============================================================================

-- ============================================================================
-- BITTI. Calisinca: paylaş menusunde "Makale Yaz" -> /makale/yeni acilir;
-- gonderilen makaleler 'pending' kaydedilir; /yonetim/makaleler sayfasindan
-- onaylayinca /makale/<slug> adresinde yayina girer ve Keşfet'te listelenir.
-- ============================================================================
