-- ============================================================================
-- Basements — Giris Takibi (sunucu tarafi, cerez ONAYINDAN BAGIMSIZ)
-- Supabase SQL Editor'da BIR KEZ calistir. Idempotent (tekrar guvenli).
--
-- Neden: Google Analytics yalniz cerez onayi veren ziyaretcileri sayar. Bu
-- tablo her basarili girisi SUNUCUDA kaydeder -> onaydan bagimsiz TAM sayim +
-- ulke. Ham IP saklanmaz (yalniz Netlify geo'dan turetilen ulke/sehir) -> KVKK.
--
-- Mevcut guvenlik modeline uyar: RLS acik, policy yok -> erisim yalniz
-- service-role (uygulamanin API route'lari + login_dashboard RPC) uzerinden.
-- ============================================================================

-- 1) "Su an online" icin son gorulme zamani. Layout her ~2 dk'da bir gunceller.
alter table public.users add column if not exists last_seen_at timestamptz;
create index if not exists idx_users_last_seen on public.users (last_seen_at desc);

-- 2) Giris olaylari. Her basarili giris/kayit bir satir ekler.
--    method: 'password' (normal giris) | 'register' (ilk kayit girisi)
--    country_* / city: Netlify x-nf-geo basligindan turetilir (ham IP YOK).
create table if not exists public.login_events (
  id           bigint generated by default as identity primary key,
  user_id      bigint not null references public.users(id) on delete cascade,
  method       text   not null default 'password',
  country_code text,          -- ISO-3166 alpha-2, or. 'TR' (bayrak + gruplamada kullanilir)
  country_name text,          -- or. 'Turkey' (Netlify Ingilizce verir)
  city         text,
  created_at   timestamptz not null default now()
);
alter table public.login_events enable row level security;

-- Panel sorgulari icin indeksler: zaman (son girisler + gunluk seri),
-- kullanici (kisi bazli), ulke (gruplama).
create index if not exists idx_login_events_created  on public.login_events (created_at desc);
create index if not exists idx_login_events_user      on public.login_events (user_id, created_at desc);
create index if not exists idx_login_events_country   on public.login_events (country_code);

-- 3) Panel icin tek turda tum ozet (sayaclar + ulke dagilimi + gunluk seri).
--    Uygulama service-role ile cagirir -> RLS'i asar, tum satirlari gorur.
--    "Bugun"/gunluk seri Istanbul saat dilimine gore hesaplanir.
create or replace function public.login_dashboard()
returns jsonb
language sql
stable
as $$
  select jsonb_build_object(
    'total',        (select count(*)::int from public.login_events),
    'today',        (select count(*)::int from public.login_events
                       where created_at >= (date_trunc('day', now() at time zone 'Europe/Istanbul')) at time zone 'Europe/Istanbul'),
    'last7',        (select count(*)::int from public.login_events where created_at >= now() - interval '7 days'),
    'last30',       (select count(*)::int from public.login_events where created_at >= now() - interval '30 days'),
    'unique_users', (select count(distinct user_id)::int from public.login_events),
    'online_now',   (select count(*)::int from public.users where last_seen_at >= now() - interval '5 minutes'),
    'countries',    coalesce((
        select jsonb_agg(to_jsonb(c) order by c.count desc)
        from (
          select country_code as code,
                 coalesce(max(country_name), country_code) as name,
                 count(*)::int as count
          from public.login_events
          where country_code is not null and country_code <> ''
          group by country_code
          order by count(*) desc
          limit 40
        ) c
    ), '[]'::jsonb),
    'daily',        coalesce((
        select jsonb_agg(to_jsonb(d) order by d.day)
        from (
          select (created_at at time zone 'Europe/Istanbul')::date as day,
                 count(*)::int as count
          from public.login_events
          where created_at >= now() - interval '13 days'
          group by 1
        ) d
    ), '[]'::jsonb)
  );
$$;

-- ============================================================================
-- BITTI. Calisinca:
--   * /api/auth/login ve /register her basarili giriste login_events'e yazar.
--   * /yonetim/istatistik (admin) paneli sayaclari + ulkeleri + son girisleri gosterir.
--   * "Su an online" = son 5 dk icinde last_seen_at guncellenen kullanicilar.
-- Admin degilsen once: update public.users set is_admin = true where username = 'KULLANICI_ADIN';
-- ============================================================================
