-- ============================================================================
-- Basements — Eşleştir (ilgi alanı eşleştirme / kart kaydırma)
-- Supabase SQL Editor'da BIR KEZ calistir. Idempotent (tekrar guvenli).
-- Guvenlik modeli digerleriyle ayni: RLS acik, policy yok -> erisim yalniz
-- service-role (uygulamanin API route'lari) + getMe() app-seviyesi auth ile.
-- ============================================================================

-- Kaydirmalar: kim kimi begendi ('like') ya da gecti ('pass').
-- unique(swiper_id, target_id) -> ayni kisi iki kez kaydirilamaz (upsert hedefi).
create table if not exists public.swipes (
  id         bigint generated by default as identity primary key,
  swiper_id  bigint not null references public.users(id) on delete cascade,
  target_id  bigint not null references public.users(id) on delete cascade,
  direction  text   not null check (direction in ('like','pass')),
  created_at timestamptz not null default now(),
  unique (swiper_id, target_id)
);
alter table public.swipes enable row level security;
create index if not exists idx_swipes_swiper      on public.swipes (swiper_id);
-- Karsilikli begeni kontrolu (target_id + direction) icin bilesik indeks.
create index if not exists idx_swipes_target_like on public.swipes (target_id, direction);

-- Eslesmeler: iki kisi birbirini begeninince olusur. user1_id < user2_id
-- (conversations ile ayni min/max deseni) -> tek satir, unique cift.
-- conversation_id: eslesme aninda bulunan/acilan DM konusmasi.
create table if not exists public.matches (
  id              bigint generated by default as identity primary key,
  user1_id        bigint not null references public.users(id) on delete cascade,
  user2_id        bigint not null references public.users(id) on delete cascade,
  conversation_id bigint references public.conversations(id) on delete set null,
  created_at      timestamptz not null default now(),
  unique (user1_id, user2_id)
);
alter table public.matches enable row level security;
create index if not exists idx_matches_user1 on public.matches (user1_id, created_at desc);
create index if not exists idx_matches_user2 on public.matches (user2_id, created_at desc);

-- ============================================================================
-- BITTI. Calisinca /eslesme aktif olur: kart destesi + karsilikli begeni ->
-- eslesme + otomatik DM konusmasi. SQL calismadan once kod defansiftir:
-- tablolar yoksa deste yine dolar ama kaydirma kaydedilmez/eslesme olmaz.
-- ============================================================================
