-- ============================================================================
-- Basements — Hikaye Öne Çıkanları (highlights) + arşiv + metinle yanıt
-- Supabase SQL Editor'da BIR KEZ calistir. Idempotent (tekrar guvenli).
--
-- Bu iki Instagram özelliği mümkün, çünkü SÜRESİ DOLMUŞ HİKAYE SATIRLARI
-- SİLİNMİYOR (sql/schema.sql:145 stories'te silme yok; app yalnızca
-- expires_at > now() ile FİLTRELİYOR). Yani 24 saat sonra satır kalıyor:
--   · Arşiv = sahibin kendi eski hikayelerini görmesi (yeni tablo YOK, sorgu meselesi)
--   · Öne çıkanlar = seçili eski hikayeleri profilde KALICI vitrine koyma
-- ============================================================================

-- ── 1) METİNLE YANIT ────────────────────────────────────────────────────────
-- Hikayeye yanıt bir DM'e düşer (Instagram'da olduğu gibi). Yanıt normal bir
-- mesajdır AMA hangi hikayeye verildiği bilgisini taşır ki sohbette "hikayene
-- yanıt verdi" + küçük önizleme gösterilebilsin. `on delete set null`: hikaye
-- silinse bile mesaj kalır, yalnız bağlamı düşer.
alter table public.messages
  add column if not exists story_id bigint references public.stories(id) on delete set null;

-- ── 2) ÖNE ÇIKANLAR ─────────────────────────────────────────────────────────
create table if not exists public.story_highlights (
  id         bigint generated by default as identity primary key,
  user_id    bigint not null references public.users(id) on delete cascade,
  title      text   not null,
  -- Vitrin dairesinin kapağı — genelde ilk hikâyenin görseli. Hikâye silinirse
  -- kapak URL'i string olarak kalır (FK değil), highlight kırılmaz.
  cover_url  text,
  created_at timestamptz default now() not null
);
alter table public.story_highlights
  drop constraint if exists story_highlights_title_check;
alter table public.story_highlights
  add constraint story_highlights_title_check check (char_length(btrim(title)) between 1 and 40);
create index if not exists idx_story_highlights_user
  on public.story_highlights (user_id, created_at desc);

create table if not exists public.story_highlight_items (
  highlight_id bigint not null references public.story_highlights(id) on delete cascade,
  story_id     bigint not null references public.stories(id) on delete cascade,
  position     integer not null default 0,
  added_at     timestamptz default now() not null,
  primary key (highlight_id, story_id)
);
create index if not exists idx_story_highlight_items_hl
  on public.story_highlight_items (highlight_id, position);

-- RLS: mevcut modele uy (RLS açık, policy yok → erişim yalnız service-role =
-- uygulamanın API route'ları; sahiplik route'ta doğrulanır).
alter table public.story_highlights      enable row level security;
alter table public.story_highlight_items enable row level security;
