-- ============================================================================
-- Basements — GERCEK KULLANICI HIZI (Real User Monitoring, cerezsiz)
-- Supabase SQL Editor'da BIR KEZ calistir. Idempotent (tekrar guvenli).
--
-- NEDEN VAR: hiz olcumlerini bugune kadar KENDI makinemizden yaptik (masaustu,
-- fiber, sicak onbellek) ve "site hizli" sonucu cikti. Ziyaretcinin gordugu
-- sey bu degil: telefonda, mobil veriyle ve BAZEN onbellek bayatken aciyor.
-- Netlify bu farki gosteremiyor -- ham HTTP istek logu yalniz Enterprise
-- planinda (Log Drains) var, Functions logu ise yalniz SUNUCU suresini yazar.
-- Bu tablo farki olcen tek arac: sureyi ZIYARETCININ TARAYICISI raporluyor.
--
-- page_views'DEN AYRI TABLO, bilerek:
--   · page_views  = kac goruntuleme (istemci gezinmeleri dahil)
--   · perf_samples = kac SAYFA ACILISI ve ne kadar surdu (yalniz ilk yukleme)
--   Iki sayinin kardinalitesi farkli; ayni tabloya sokmak ikisini de bozardi.
--   Ayrica calisan istatistik hattina (2629 satir) hic dokunmamis oluyoruz.
--
-- GIZLILIK (KVKK/GDPR): cerez yok, onay gerekmez, ham IP saklanmaz, ziyaretci
-- kimligi TUTULMAZ (visitor_hash bile yok -- olculen sayfa, kisi degil).
-- Guvenlik: RLS acik, policy yok -> yalniz service-role (uygulama) erisir.
-- ============================================================================

create table if not exists public.perf_samples (
  id           bigint generated by default as identity primary key,
  path         text   not null,
  -- Core Web Vitals + klasik zamanlamalar. Hepsi nullable: tarayici
  -- desteklemiyorsa (Safari'de INP yok) o sutun bos gecer, satir yine yazilir.
  ttfb_ms      int,                 -- navigation.responseStart
  fcp_ms       int,                 -- first-contentful-paint
  lcp_ms       int,                 -- largest-contentful-paint  ← ASIL METRIK
  load_ms      int,                 -- loadEventEnd
  inp_ms       int,                 -- en kotu etkilesim gecikmesi (INP yaklasigi)
  cls_x1000    int,                 -- CLS × 1000 (0.083 -> 83); tam sayi saklanir
  nav_type     text,                -- navigate | reload | back_forward
  device       text,                -- mobil | masaustu
  conn         text,                -- 4g | 3g | 2g | slow-2g (mobil veri kalitesi)
  country_code text,
  created_at   timestamptz not null default now()
);
alter table public.perf_samples enable row level security;

create index if not exists idx_perf_created on public.perf_samples (created_at desc);
create index if not exists idx_perf_path    on public.perf_samples (path);

-- ============================================================================
-- Panel ozeti. ORTALAMA DEGIL YUZDELIK kullanilir: tek bir 12 saniyelik acilis
-- ortalamayi zehirler, oysa "ziyaretcilerin %75'i su sureden hizli gordu"
-- cumlesi hem dogru hem de Google'in Core Web Vitals esikleriyle ayni dil.
-- ============================================================================
create or replace function public.perf_dashboard()
returns jsonb
language sql
stable
as $$
  with son as (
    select * from public.perf_samples where created_at >= now() - interval '30 days'
  )
  select jsonb_build_object(
    'orneklem_toplam', (select count(*)::int from public.perf_samples),
    'orneklem_30',     (select count(*)::int from son),
    'orneklem_7',      (select count(*)::int from son where created_at >= now() - interval '7 days'),

    -- Ana tablo: her metrigin p50 / p75 / p95'i (son 30 gun).
    'metrikler', coalesce((
      select jsonb_agg(to_jsonb(m) order by m.sira)
      from (
        select 1 as sira, 'TTFB' as ad, 'Sunucu ilk baytı' as aciklama, 800 as iyi, 1800 as kotu,
               (percentile_cont(0.50) within group (order by ttfb_ms))::int as p50,
               (percentile_cont(0.75) within group (order by ttfb_ms))::int as p75,
               (percentile_cont(0.95) within group (order by ttfb_ms))::int as p95,
               count(ttfb_ms)::int as n
        from son
        union all
        select 2, 'FCP', 'İlk yazı/görsel göründü', 1800, 3000,
               (percentile_cont(0.50) within group (order by fcp_ms))::int,
               (percentile_cont(0.75) within group (order by fcp_ms))::int,
               (percentile_cont(0.95) within group (order by fcp_ms))::int,
               count(fcp_ms)::int
        from son
        union all
        select 3, 'LCP', 'En büyük içerik göründü', 2500, 4000,
               (percentile_cont(0.50) within group (order by lcp_ms))::int,
               (percentile_cont(0.75) within group (order by lcp_ms))::int,
               (percentile_cont(0.95) within group (order by lcp_ms))::int,
               count(lcp_ms)::int
        from son
        union all
        select 4, 'INP', 'Dokunmaya yanıt süresi', 200, 500,
               (percentile_cont(0.50) within group (order by inp_ms))::int,
               (percentile_cont(0.75) within group (order by inp_ms))::int,
               (percentile_cont(0.95) within group (order by inp_ms))::int,
               count(inp_ms)::int
        from son
        union all
        select 5, 'Yükleme', 'Sayfa tamamen yüklendi', 3000, 6000,
               (percentile_cont(0.50) within group (order by load_ms))::int,
               (percentile_cont(0.75) within group (order by load_ms))::int,
               (percentile_cont(0.95) within group (order by load_ms))::int,
               count(load_ms)::int
        from son
      ) m
    ), '[]'::jsonb),

    -- LCP'nin Google esiklerine gore dagilimi. Panelde tek cumleye donusur:
    -- "ziyaretcilerin %X'i sayfayi 2,5 sn'den once gordu".
    'lcp_dagilim', (
      select jsonb_build_object(
        'iyi',   count(*) filter (where lcp_ms <= 2500)::int,
        'orta',  count(*) filter (where lcp_ms > 2500 and lcp_ms <= 4000)::int,
        'kotu',  count(*) filter (where lcp_ms > 4000)::int
      ) from son where lcp_ms is not null
    ),

    -- CLS ayri: yuzdelik degil, esik gecen oran anlamli (p75 <= 0.1 hedef).
    'cls_p75', (select (percentile_cont(0.75) within group (order by cls_x1000))::int from son),

    -- Cihaz kirilimi. ASIL SORUYU BU CEVAPLIYOR: masaustunde olctugumuz sure
    -- ile telefondaki sure arasindaki fark buradan gorunur.
    'cihazlar', coalesce((
      select jsonb_agg(to_jsonb(d) order by d.n desc)
      from (
        select coalesce(device, 'bilinmiyor') as cihaz,
               count(*)::int as n,
               (percentile_cont(0.75) within group (order by lcp_ms))::int as lcp_p75,
               (percentile_cont(0.75) within group (order by ttfb_ms))::int as ttfb_p75
        from son group by 1
      ) d
    ), '[]'::jsonb),

    -- Baglanti kalitesi (4g / 3g / slow-2g). "Mobil veriyle mi yavas?" sorusu.
    'baglantilar', coalesce((
      select jsonb_agg(to_jsonb(c) order by c.n desc)
      from (
        select coalesce(conn, 'bilinmiyor') as tur,
               count(*)::int as n,
               (percentile_cont(0.75) within group (order by lcp_ms))::int as lcp_p75
        from son group by 1
      ) c
    ), '[]'::jsonb),

    -- Sayfa bazinda. Hangi sayfa gercekten agir, tahminle degil olcumle.
    'sayfalar', coalesce((
      select jsonb_agg(to_jsonb(p) order by p.n desc)
      from (
        select path,
               count(*)::int as n,
               (percentile_cont(0.75) within group (order by lcp_ms))::int as lcp_p75,
               (percentile_cont(0.75) within group (order by ttfb_ms))::int as ttfb_p75,
               max(ttfb_ms)::int as ttfb_max
        from son group by path
        order by count(*) desc
        limit 20
      ) p
    ), '[]'::jsonb),

    -- Gunluk p75 LCP (son 14 gun) — deploy sonrasi iyilesme/bozulma trendi.
    'gunluk', coalesce((
      select jsonb_agg(to_jsonb(g) order by g.day)
      from (
        select (created_at at time zone 'Europe/Istanbul')::date as day,
               count(*)::int as n,
               (percentile_cont(0.75) within group (order by lcp_ms))::int as lcp_p75
        from public.perf_samples
        where created_at >= now() - interval '13 days'
        group by 1
      ) g
    ), '[]'::jsonb),

    -- SOGUK VURUS SAYACI. TTFB > 1000 ms olan acilislar = onbellek bayatken
    -- gelip yeniden uretimi BEKLEYEN ziyaretciler. Suphenin sayisal karsiligi.
    'soguk', (
      select jsonb_build_object(
        'adet',  count(*) filter (where ttfb_ms > 1000)::int,
        'toplam', count(ttfb_ms)::int,
        'ornekler', coalesce((
          select jsonb_agg(to_jsonb(s))
          from (
            select path, ttfb_ms, lcp_ms, created_at
            from son where ttfb_ms > 1000
            order by created_at desc limit 10
          ) s
        ), '[]'::jsonb)
      ) from son
    )
  );
$$;

-- ============================================================================
-- BITTI. Calisinca: her SAYFA ACILISINDA (istemci gezinmeleri degil) ziyaretci
-- tarayicisi TTFB/FCP/LCP/INP/CLS raporlar; panelde /yonetim/istatistik
-- "Gercek kullanici hizi" bolumu dolar.
--
-- ILK VERI: birkac gercek ziyaret gerekir. Kendi tarayicindan canli siteyi
-- acmak da sayilir (localhost SAYILMAZ -- gelistirme trafigi disarida).
--
-- Bakim (opsiyonel, tablo buyurse):
--   delete from public.perf_samples where created_at < now() - interval '180 days';
-- ============================================================================
