-- ============================================================================
-- Basements — "Bilgi Karti" (did_you_know) + Gunun Sorusu / XP / Seri / Rozet
-- Supabase SQL Editor'da BIR KEZ calistir. Idempotent: tekrar calistirmak guvenli.
-- Mevcut guvenlik modeline uyar: RLS acik, policy yok -> erisim yalniz service-role
-- (uygulamanin API route'lari) uzerinden, getMe() app-seviyesi auth ile.
-- ============================================================================


-- ============================================================================
-- OZELLIK 1 — Bilgi Kartlari (did_you_know)
-- ============================================================================
create table if not exists public.did_you_know (
  id           bigint generated by default as identity primary key,
  user_id      bigint references public.users(id) on delete set null,
  title        text not null,
  body         text not null,
  source_url   text,
  source_label text,
  article_slug text,
  image_url    text,
  active       boolean not null default true,
  created_at   timestamptz not null default now()
);
alter table public.did_you_know enable row level security;
create index if not exists idx_dyk_active_created on public.did_you_know (active, created_at desc);

-- Ornek bilgi kartlari (mevcut makalelere bagli) -> SQL'i calistirinca feed'de
-- hemen gorunsunler. Yalnizca tablo BOSSA ekle (tekrar calistirinca cogalmaz).
insert into public.did_you_know (title, body, source_label, article_slug)
select * from (values
  ('Mitokondrin bir zamanlar bagimsiz bir bakteriydi',
   'Hucrelerimize enerji ureten mitokondri, milyarlarca yil once serbest yasayan bir bakteriydi. Baska bir hucre onu yuttu ama sindirmedi; ikisi ortak yasamaya basladi. Bugun hala kendi DNA''sini tasir.',
   'Endosimbiyoz', 'endosimbiyoz'),
  ('Dunyadaki en kalabalik biyolojik varlik bir virustur',
   'Bakteriyofajlar bakterileri enfekte eden viruslerdir ve gezegendeki en kalabalik biyolojik varliktir; sayilari 10^31 tahmin edilir. Okyanusta her saniye bakterilerin buyuk kismini oldururler.',
   'Bakteriyofaj', 'bakteriyofaj'),
  ('Bir ambulansin sireni aslinda hic degismez',
   'Ambulans yaklasirken tiz, uzaklasirken pes duyarsin; ama sirenin gercek frekansi sabittir. Degisen sey ses dalgalarinin sana ulasma bicimidir. Buna Doppler etkisi denir.',
   'Doppler Etkisi', 'doppler'),
  ('Evrenin genisledigini bir renk kaymasi ele verdi',
   'Uzak galaksilerin isigi kirmiziya kayar; yani bizden uzaklasirlar. Edwin Hubble 1929''da bunu fark etti ve evrenin genisledigini gosterdi. Bu da Doppler etkisinin isiktaki halidir.',
   'Doppler Etkisi', 'doppler'),
  ('Hat sanatini goz kararindan matematige Ibn Mukle tasidi',
   'Islam hattini olculu bir sisteme oturtan kisi Ibn Mukle''dir: harfleri bir noktanin katlariyla oranlayarak guzelligi matematige bagladi.',
   'Kaligrafi', 'kaligrafi')
) as v(title, body, source_label, article_slug)
where not exists (select 1 from public.did_you_know);


-- ============================================================================
-- OZELLIK 2 — Gunun Sorusu / XP / Seri / Rozet
-- ============================================================================

-- Soru havuzu
create table if not exists public.quiz_questions (
  id            bigint generated by default as identity primary key,
  question      text   not null,
  options       jsonb  not null,         -- ["A secenegi","B","C","D"]
  correct_index int    not null,         -- 0 tabanli dogru cevap indeksi
  explanation   text,
  article_slug  text,                    -- opsiyonel: kaynak makale
  active        boolean not null default true,
  created_at    timestamptz not null default now()
);
alter table public.quiz_questions enable row level security;
create index if not exists idx_quiz_active on public.quiz_questions (active, id);

-- Kullanici ilerlemesi (XP, seri, sayaclar)
create table if not exists public.user_progress (
  user_id          bigint primary key references public.users(id) on delete cascade,
  xp               int  not null default 0,
  current_streak   int  not null default 0,
  longest_streak   int  not null default 0,
  last_answer_date date,
  total_correct    int  not null default 0,
  total_answered   int  not null default 0,
  updated_at       timestamptz not null default now()
);
alter table public.user_progress enable row level security;

-- Gunde tek cevap. (user_id, answer_date) PK -> ayni gun ikinci cevabi engeller.
create table if not exists public.daily_answers (
  user_id        bigint  not null references public.users(id) on delete cascade,
  answer_date    date    not null,
  question_id    bigint  not null references public.quiz_questions(id),
  selected_index int     not null,
  is_correct     boolean not null,
  created_at     timestamptz not null default now(),
  primary key (user_id, answer_date)
);
alter table public.daily_answers enable row level security;

-- Kazanilan rozetler
create table if not exists public.user_badges (
  user_id   bigint not null references public.users(id) on delete cascade,
  badge_key text   not null,
  earned_at timestamptz not null default now(),
  primary key (user_id, badge_key)
);
alter table public.user_badges enable row level security;

-- Soru havuzu tohumu (makale quizlerinden). Yalnizca havuz BOSSA ekle.
insert into public.quiz_questions (question, options, correct_index, explanation, article_slug)
select * from (values
  ('Bir ambulans yaninizdan gecerken aslinda degisen nedir?',
   '["Sirenin gercek frekansi","Sesin size ulasma bicimi (duydugunuz frekans)","Havanin sicakligi","Sirenin ses duzeyi"]'::jsonb, 1,
   'Kaynagin gercek frekansi sabittir; hareket, dalgalarin size ulasma bicimini degistirir. Buna Doppler etkisi denir.', 'doppler'),
  ('Isikta "maviye kayma" ne anlama gelir?',
   '["Kaynak bizden uzaklasiyor","Kaynak bize yaklasiyor (dalga boyu kisalir)","Kaynak duruyor","Kaynak isiniyor"]'::jsonb, 1,
   'Maviye kayma kaynagin yaklastigini, kirmiziya kayma uzaklastigini gosterir.', 'doppler'),
  ('Evrenin genisledigi fikri hangi gozlemden dogdu?',
   '["Ayin evrelerinden","Uzak galaksilerin kirmiziya kaymasindan (Hubble, 1929)","Gunes lekelerinden","Meteor yagmurlarindan"]'::jsonb, 1,
   'Hubble uzak galaksilerin isiginin kirmiziya kaydigini olcerek evrenin genisledigini gosterdi.', 'doppler'),
  ('Hucrelerimizdeki mitokondrinin kokeni nedir?',
   '["Cekirdegin bir parcasi","Bir zamanlar serbest yasayan bir bakteri","Bir virus","Cansiz bir kristal"]'::jsonb, 1,
   'Endosimbiyotik kurama gore mitokondri, yutulup sindirilmeyen bir bakteriden gelir.', 'endosimbiyoz'),
  ('Endosimbiyotik kurami kanitlariyla kabul ettiren bilim insani kimdir?',
   '["Charles Darwin","Lynn Margulis","Gregor Mendel","Louis Pasteur"]'::jsonb, 1,
   'Lynn Margulis 1960''larda kurami kanitlarla savunup bilim dunyasina kabul ettirdi.', 'endosimbiyoz'),
  ('Bakteriyofaj nedir?',
   '["Insani enfekte eden bir bakteri","Bakterileri enfekte eden bir virus","Bir antibiyotik turu","Bir mantar"]'::jsonb, 1,
   'Faj, bakteri yiyen (enfekte eden) bir virustur.', 'bakteriyofaj'),
  ('Litik dongunun sonunda bakteriye ne olur?',
   '["Saglikli kalir","Lizin enzimiyle patlar ve yuzlerce faj sacilir","Daha hizli cogalir","Antibiyotige donusur"]'::jsonb, 1,
   'Litik dongude konak hucre parcalanir (lizis) ve yeni fajlar saçilir.', 'bakteriyofaj'),
  ('"Kaligrafi" kelimesi hangi koklerden gelir?',
   '["Latince calidus + grafia","Yunanca kallos (guzellik) + graphein (yazmak)","Arapca hat + husn","Cince shu + fa"]'::jsonb, 1,
   'Kaligrafi = kallos (guzellik) + graphein (yazmak).', 'kaligrafi'),
  ('Islam hattini olculu bir matematiksel sisteme oturtan kisi kimdir?',
   '["Yakut el-Mustasimi","Ibn Mukle","Seyh Hamdullah","Hafiz Osman"]'::jsonb, 1,
   'Ibn Mukle harfleri bir noktanin katlariyla oranlayan olculu hat sistemini kurdu.', 'kaligrafi'),
  ('Mitokondrinin bakteriyel kokenine asagidakilerden hangisi KANIT DEGILDIR?',
   '["Kendi halkasal DNA''si","70S bakteriyel ribozomlari","Cekirdekte kromozomlara paketlenmis DNA''si","Cift zari"]'::jsonb, 2,
   'Mitokondrinin DNA''si halkasaldir ve cekirdekten bagimsizdir; kromozomlara paketli degildir.', 'endosimbiyoz')
) as v(question, options, correct_index, explanation, article_slug)
where not exists (select 1 from public.quiz_questions);

-- ============================================================================
-- BITTI. Hata almazsan iki ozellik de aktif olur:
--  - Bilgi kartlari ana feed'e serpistirilir (her ~4 gonderide bir).
--  - Ana sayfada "Gunun Sorusu" widget'i + profilde XP/seri/rozet gorunur.
-- ============================================================================
