-- ============================================================================
-- Basements — Ziyaretci Takibi (cerezsiz, ONAYSIZ, sunucu tarafi)
-- Supabase SQL Editor'da BIR KEZ calistir. Idempotent (tekrar guvenli).
--
-- Neden: Google Analytics yalniz cerez ONAYI verenleri sayar; onaylamayanlar
-- gorunmez. Bu tablo, uye olsun olmasin HER sayfa goruntulemeyi sunucuda,
-- cerezsiz kaydeder -> onaya gerek yok, herkes sayilir.
--
-- Gizlilik (KVKK/GDPR): ham IP SAKLANMAZ. Tekil ziyaretci, gunluk DONEN bir
-- hash ile (IP+tarayici+gun+gizli tuz) yaklasik sayilir; ertesi gun ayni kisi
-- farkli hash uretir -> gunler arasi takip edilemez (Plausible/Fathom yontemi).
--
-- Guvenlik: RLS acik, policy yok -> yalniz service-role (uygulama) erisir.
-- ============================================================================

create table if not exists public.page_views (
  id           bigint generated by default as identity primary key,
  path         text   not null,
  country_code text,                          -- ISO alpha-2 (Netlify geo)
  country_name text,
  visitor_hash text,                          -- gunluk donen gizlilik hash'i
  created_at   timestamptz not null default now()
);
alter table public.page_views enable row level security;

create index if not exists idx_page_views_created on public.page_views (created_at desc);
create index if not exists idx_page_views_country on public.page_views (country_code);
create index if not exists idx_page_views_path    on public.page_views (path);
create index if not exists idx_page_views_hash    on public.page_views (visitor_hash, created_at desc);

-- Tek turda tum trafik ozeti (panel icin). "Bugun"/gunluk seri Istanbul tz.
--   online = son 5 dk'da aktif (goruntuleme yapan) farkli ziyaretci
--   uniques = farkli visitor_hash (yaklasik "kac kisi")
--   views   = ham sayfa goruntuleme
create or replace function public.traffic_dashboard()
returns jsonb
language sql
stable
as $$
  select jsonb_build_object(
    'online_now',     (select count(distinct visitor_hash)::int from public.page_views where created_at >= now() - interval '5 minutes'),
    'views_today',    (select count(*)::int from public.page_views
                         where created_at >= (date_trunc('day', now() at time zone 'Europe/Istanbul')) at time zone 'Europe/Istanbul'),
    'views_7',        (select count(*)::int from public.page_views where created_at >= now() - interval '7 days'),
    'views_total',    (select count(*)::int from public.page_views),
    'uniques_today',  (select count(distinct visitor_hash)::int from public.page_views
                         where created_at >= (date_trunc('day', now() at time zone 'Europe/Istanbul')) at time zone 'Europe/Istanbul'),
    'uniques_7',      (select count(distinct visitor_hash)::int from public.page_views where created_at >= now() - interval '7 days'),
    'countries',      coalesce((
        select jsonb_agg(to_jsonb(c) order by c.count desc)
        from (
          select country_code as code,
                 coalesce(max(country_name), country_code) as name,
                 count(distinct visitor_hash)::int as count
          from public.page_views
          where country_code is not null and country_code <> '' and created_at >= now() - interval '30 days'
          group by country_code
          order by count(distinct visitor_hash) desc
          limit 40
        ) c
    ), '[]'::jsonb),
    'top_pages',      coalesce((
        select jsonb_agg(to_jsonb(p) order by p.views desc)
        from (
          select path,
                 count(*)::int as views,
                 count(distinct visitor_hash)::int as uniques
          from public.page_views
          where created_at >= now() - interval '30 days'
          group by path
          order by count(*) desc
          limit 20
        ) p
    ), '[]'::jsonb),
    'daily',          coalesce((
        select jsonb_agg(to_jsonb(d) order by d.day)
        from (
          select (created_at at time zone 'Europe/Istanbul')::date as day,
                 count(*)::int as views,
                 count(distinct visitor_hash)::int as uniques
          from public.page_views
          where created_at >= now() - interval '13 days'
          group by 1
        ) d
    ), '[]'::jsonb)
  );
$$;

-- ============================================================================
-- BITTI. Calisinca: her sayfa goruntuleme (uye/anonim) kaydedilir; panelde
-- /yonetim/istatistik "Trafik" bolumu dolar (online, tekil ziyaretci, gunluk
-- seri, ulke dagilimi, en cok gezilen sayfalar). Botlar ve /yonetim haric.
--
-- Tablo buyurse (opsiyonel bakim): eski satirlari periyodik silebilirsin, or.
--   delete from public.page_views where created_at < now() - interval '180 days';
-- ============================================================================
