-- ============================================================================
-- Basements — Makale Tartismasi + Okuma Listesi (Fikir 5)
-- Supabase SQL Editor'da BIR KEZ calistir. Idempotent (tekrar guvenli).
-- Mevcut guvenlik modeline uyar: RLS acik, policy yok -> erisim yalniz
-- service-role (uygulamanin API route'lari) + getMe() app-seviyesi auth ile.
-- Makaleler DB'de degil; article_slug bir string anahtardir (orn 'doppler').
-- ============================================================================

-- Makale yorumlari (duz; thread yok). Fikir 4 (ilgili konular/rastgele) SQL gerektirmez.
create table if not exists public.article_comments (
  id           bigint generated by default as identity primary key,
  article_slug text   not null,
  user_id      bigint not null references public.users(id) on delete cascade,
  content      text   not null,
  created_at   timestamptz not null default now()
);
alter table public.article_comments enable row level security;
create index if not exists idx_article_comments_slug_created
  on public.article_comments (article_slug, created_at);

-- Okuma listesi (makale kaydetme). Composite PK (user_id, article_slug) ->
-- ayni makale iki kez kaydedilemez; fact_reposts ile ayni desen.
create table if not exists public.article_saves (
  user_id      bigint not null references public.users(id) on delete cascade,
  article_slug text   not null,
  created_at   timestamptz not null default now(),
  primary key (user_id, article_slug)
);
alter table public.article_saves enable row level security;
create index if not exists idx_article_saves_user_created
  on public.article_saves (user_id, created_at desc);

-- ============================================================================
-- BITTI. Calisinca her makalenin altinda Tartisma (yorum) + Kaydet aktif olur
-- ve /okuma-listesi sayfasi dolar. (Ilgili Konular + Rastgele zaten calisiyordu.)
-- ============================================================================
