-- ============================================================================
-- Basements — "Bilgi Kartı" (did_you_know) + Günün Sorusu / XP / Seri / Rozet
-- Supabase SQL Editor'da BİR KEZ çalıştır. Idempotent: tekrar çalıştırmak güvenli.
-- Mevcut güvenlik modeline uyar: RLS açık, policy yok -> erişim yalnız service-role
-- (uygulamanın API route'ları) üzerinden, getMe() app-seviyesi auth ile.
-- ============================================================================


-- ============================================================================
-- ÖZELLİK 1 — Bilgi Kartları (did_you_know)
-- ============================================================================
create table if not exists public.did_you_know (
  id           bigint generated by default as identity primary key,
  user_id      bigint references public.users(id) on delete set null,
  title        text not null,
  body         text not null,
  source_url   text,
  source_label text,
  article_slug text,
  image_url    text,
  active       boolean not null default true,
  created_at   timestamptz not null default now()
);
alter table public.did_you_know enable row level security;
create index if not exists idx_dyk_active_created on public.did_you_know (active, created_at desc);

-- Örnek bilgi kartları (mevcut makalelere bağlı) -> SQL'i çalıştırınca feed'de
-- hemen görünsünler. Yalnızca tablo BOŞSA ekle (tekrar çalıştırınca çoğalmaz).
insert into public.did_you_know (title, body, source_label, article_slug)
select * from (values
  ('Mitokondri bir zamanlar bağımsız bir bakteriydi',
   'Hücrelerimize enerji üreten mitokondri, milyarlarca yıl önce serbest yaşayan bir bakteriydi. Başka bir hücre onu yuttu ama sindirmedi; ikisi ortak yaşamaya başladı. Bugün hâlâ kendi DNA''sını taşır.',
   'Endosimbiyoz', 'endosimbiyoz'),
  ('Dünyadaki en kalabalık biyolojik varlık bir virüstür',
   'Bakteriyofajlar bakterileri enfekte eden virüslerdir ve gezegendeki en kalabalık biyolojik varlıktır; sayıları 10^31 tahmin edilir. Okyanusta her saniye bakterilerin büyük kısmını öldürürler.',
   'Bakteriyofaj', 'bakteriyofaj'),
  ('Bir ambulansın sireni aslında hiç değişmez',
   'Ambulans yaklaşırken tiz, uzaklaşırken pes duyarsın; ama sirenin gerçek frekansı sabittir. Değişen şey ses dalgalarının sana ulaşma biçimidir. Buna Doppler etkisi denir.',
   'Doppler Etkisi', 'doppler'),
  ('Evrenin genişlediğini bir renk kayması ele verdi',
   'Uzak galaksilerin ışığı kırmızıya kayar; yani bizden uzaklaşırlar. Edwin Hubble 1929''da bunu fark etti ve evrenin genişlediğini gösterdi. Bu da Doppler etkisinin ışıktaki hâlidir.',
   'Doppler Etkisi', 'doppler'),
  ('Hat sanatını göz kararından matematiğe İbn Mukle taşıdı',
   'İslam hattını ölçülü bir sisteme oturtan kişi İbn Mukle''dir: harfleri bir noktanın katlarıyla oranlayarak güzelliği matematiğe bağladı.',
   'Kaligrafi', 'kaligrafi')
) as v(title, body, source_label, article_slug)
where not exists (select 1 from public.did_you_know);


-- ============================================================================
-- ÖZELLİK 2 — Günün Sorusu / XP / Seri / Rozet
-- ============================================================================

-- Soru havuzu
create table if not exists public.quiz_questions (
  id            bigint generated by default as identity primary key,
  question      text   not null,
  options       jsonb  not null,         -- ["A secenegi","B","C","D"]
  correct_index int    not null,         -- 0 tabanli dogru cevap indeksi
  explanation   text,
  article_slug  text,                    -- opsiyonel: kaynak makale
  active        boolean not null default true,
  created_at    timestamptz not null default now()
);
alter table public.quiz_questions enable row level security;
create index if not exists idx_quiz_active on public.quiz_questions (active, id);

-- Kullanici ilerlemesi (XP, seri, sayaclar)
create table if not exists public.user_progress (
  user_id          bigint primary key references public.users(id) on delete cascade,
  xp               int  not null default 0,
  current_streak   int  not null default 0,
  longest_streak   int  not null default 0,
  last_answer_date date,
  total_correct    int  not null default 0,
  total_answered   int  not null default 0,
  updated_at       timestamptz not null default now()
);
alter table public.user_progress enable row level security;

-- Gunde tek cevap. (user_id, answer_date) PK -> ayni gun ikinci cevabi engeller.
create table if not exists public.daily_answers (
  user_id        bigint  not null references public.users(id) on delete cascade,
  answer_date    date    not null,
  question_id    bigint  not null references public.quiz_questions(id),
  selected_index int     not null,
  is_correct     boolean not null,
  created_at     timestamptz not null default now(),
  primary key (user_id, answer_date)
);
alter table public.daily_answers enable row level security;

-- Kazanilan rozetler
create table if not exists public.user_badges (
  user_id   bigint not null references public.users(id) on delete cascade,
  badge_key text   not null,
  earned_at timestamptz not null default now(),
  primary key (user_id, badge_key)
);
alter table public.user_badges enable row level security;

-- Soru havuzu tohumu (makale quizlerinden). Yalnızca havuz BOŞSA ekle.
insert into public.quiz_questions (question, options, correct_index, explanation, article_slug)
select * from (values
  ('Bir ambulans yanınızdan geçerken aslında değişen nedir?',
   '["Sirenin gerçek frekansı","Sesin size ulaşma biçimi (duyduğunuz frekans)","Havanın sıcaklığı","Sirenin ses düzeyi"]'::jsonb, 1,
   'Kaynağın gerçek frekansı sabittir; hareket, dalgaların size ulaşma biçimini değiştirir. Buna Doppler etkisi denir.', 'doppler'),
  ('Işıkta "maviye kayma" ne anlama gelir?',
   '["Kaynak bizden uzaklaşıyor","Kaynak bize yaklaşıyor (dalga boyu kısalır)","Kaynak duruyor","Kaynak ısınıyor"]'::jsonb, 1,
   'Maviye kayma kaynağın yaklaştığını, kırmızıya kayma uzaklaştığını gösterir.', 'doppler'),
  ('Evrenin genişlediği fikri hangi gözlemden doğdu?',
   '["Ayın evrelerinden","Uzak galaksilerin kırmızıya kaymasından (Hubble, 1929)","Güneş lekelerinden","Meteor yağmurlarından"]'::jsonb, 1,
   'Hubble uzak galaksilerin ışığının kırmızıya kaydığını ölçerek evrenin genişlediğini gösterdi.', 'doppler'),
  ('Hücrelerimizdeki mitokondrinin kökeni nedir?',
   '["Çekirdeğin bir parçası","Bir zamanlar serbest yaşayan bir bakteri","Bir virüs","Cansız bir kristal"]'::jsonb, 1,
   'Endosimbiyotik kurama göre mitokondri, yutulup sindirilmeyen bir bakteriden gelir.', 'endosimbiyoz'),
  ('Endosimbiyotik kuramı kanıtlarıyla kabul ettiren bilim insanı kimdir?',
   '["Charles Darwin","Lynn Margulis","Gregor Mendel","Louis Pasteur"]'::jsonb, 1,
   'Lynn Margulis 1960''larda kuramı kanıtlarla savunup bilim dünyasına kabul ettirdi.', 'endosimbiyoz'),
  ('Bakteriyofaj nedir?',
   '["İnsanı enfekte eden bir bakteri","Bakterileri enfekte eden bir virüs","Bir antibiyotik türü","Bir mantar"]'::jsonb, 1,
   'Faj, bakteri yiyen (enfekte eden) bir virüstür.', 'bakteriyofaj'),
  ('Litik döngünün sonunda bakteriye ne olur?',
   '["Sağlıklı kalır","Lizin enzimiyle patlar ve yüzlerce faj saçılır","Daha hızlı çoğalır","Antibiyotiğe dönüşür"]'::jsonb, 1,
   'Litik döngüde konak hücre parçalanır (lizis) ve yeni fajlar saçılır.', 'bakteriyofaj'),
  ('"Kaligrafi" kelimesi hangi köklerden gelir?',
   '["Latince calidus + grafia","Yunanca kallos (güzellik) + graphein (yazmak)","Arapça hat + hüsn","Çince shu + fa"]'::jsonb, 1,
   'Kaligrafi = kallos (güzellik) + graphein (yazmak).', 'kaligrafi'),
  ('İslam hattını ölçülü bir matematiksel sisteme oturtan kişi kimdir?',
   '["Yakut el-Mustasimi","İbn Mukle","Şeyh Hamdullah","Hafız Osman"]'::jsonb, 1,
   'İbn Mukle harfleri bir noktanın katlarıyla oranlayan ölçülü hat sistemini kurdu.', 'kaligrafi'),
  ('Mitokondrinin bakteriyel kökenine aşağıdakilerden hangisi KANIT DEĞİLDİR?',
   '["Kendi halkasal DNA''sı","70S bakteriyel ribozomları","Çekirdekte kromozomlara paketlenmiş DNA''sı","Çift zarı"]'::jsonb, 2,
   'Mitokondrinin DNA''sı halkasaldır ve çekirdekten bağımsızdır; kromozomlara paketli değildir.', 'endosimbiyoz')
) as v(question, options, correct_index, explanation, article_slug)
where not exists (select 1 from public.quiz_questions);

-- ============================================================================
-- BİTTİ. Hata almazsan iki özellik de aktif olur:
--  - Bilgi kartları ana feed'e serpiştirilir (her ~4 gönderide bir).
--  - Ana sayfada "Günün Sorusu" widget'ı + profilde XP/seri/rozet görünür.
-- ============================================================================
