-- ═══════════════════════════════════════════════════════════════════════════
-- BASEMENTS — VERİTABANI ŞEMASI
-- Canlı veritabanından dökülmüştür: 2026-07-18
--
-- NEDEN VAR: bu tabloların hiçbirinin tanımı depoda yoktu; hepsi Supabase
-- arayüzünden elle oluşturulmuştu. Yani yapı TEK KOPYA hâlinde yalnızca canlı
-- veritabanında duruyordu. Bir `alter table` yanlış çalışsa ya da bir politika
-- kazara düşse "eskiden nasıldı?" sorusunun cevabı hiçbir yerde yoktu.
-- Artık `git diff` ile sapma görünür.
--
-- NASIL ÜRETİLDİ: sql/_schema-dump-query.sql içindeki 7 sorgu. `supabase db
-- dump` kullanılamadı (Docker → WSL2 → yönetici hakkı + yeniden başlatma
-- zinciri istiyor); ayrıca `--schema public` ile alınan bir dump 5. bölümdeki
-- auth.users trigger'ını KAÇIRIRDI.
--
-- ⚠️ İKİ UYARI
--  1. VERİ İÇERMEZ. Yalnızca yapı. (users tablosunda e-posta ve doğum tarihi
--     var — veri içeren bir dosya asla git'e girmemeli.)
--  2. `id` kolonlarının ÜRETİM YÖNTEMİ ÇIKARIMDIR. Canlıda `nextval(...)`
--     default'u görünenler (users, posts, quick_facts, spotify_playlists,
--     youtube_items, game_scores) aslında serial/sequence; diğerleri identity
--     varsayıldı. Hepsi burada `generated by default as identity` yazıldı.
--     Bu dosyayla SIFIRDAN bir ortam kuracaksan o kolonları önce doğrula.
--
-- KAPSAMAZ: sequence sahiplikleri, GRANT/REVOKE, extension'lar, view'ler,
-- composite type'lar, `public` dışındaki şemaların tabloları.
-- ═══════════════════════════════════════════════════════════════════════════


-- ═══════════════════════════════════════════════════════════════════════════
-- 1 · TABLOLAR
-- ═══════════════════════════════════════════════════════════════════════════

create table if not exists public.users (
  id                  bigint generated by default as identity not null,
  username            text not null,
  display_name        text not null,
  avatar              text default '/avatars/default.png'::text,
  bio                 text default ''::text,
  created_at          timestamptz default now(),
  auth_id             uuid,
  email               text,
  is_private          boolean default false not null,
  dm_privacy          text default 'everyone'::text not null,
  comment_privacy     text default 'everyone'::text not null,
  birthdate           date,
  location            text,
  website             text,
  gender              text default ''::text not null,
  interests           text[] default '{}'::text[] not null,
  name_changed_at     timestamptz,
  username_changed_at timestamptz,
  is_admin            boolean default false not null,
  last_seen_at        timestamptz,
  terms_accepted_at   timestamptz,
  is_deleted          boolean default false not null
);

create table if not exists public.quick_facts (
  id         bigint generated by default as identity not null,
  user_id    bigint not null,
  caption    text not null,
  media_url  text not null,
  media_type text not null,
  likes      integer default 0,
  created_at timestamptz default now(),
  media      jsonb default '[]'::jsonb not null
);

create table if not exists public.posts (
  id         bigint generated by default as identity not null,
  user_id    bigint not null,
  content    text not null,
  image_url  text,
  category   text default 'general'::text,
  likes      integer default 0,
  created_at timestamptz default now(),
  reposts    integer default 0 not null
);

create table if not exists public.comments (
  id         bigint generated by default as identity not null,
  post_id    bigint not null,
  user_id    bigint not null,
  content    text not null,
  created_at timestamptz default now() not null,
  parent_id  bigint
);

create table if not exists public.fact_likes (
  user_id    bigint not null,
  fact_id    bigint not null,
  created_at timestamptz default now() not null
);

create table if not exists public.post_likes (
  user_id    bigint not null,
  post_id    bigint not null,
  created_at timestamptz default now() not null
);

create table if not exists public.fact_reposts (
  user_id    bigint not null,
  fact_id    bigint not null,
  created_at timestamptz default now() not null
);

create table if not exists public.reposts (
  user_id    bigint not null,
  post_id    bigint not null,
  created_at timestamptz default now() not null
);

create table if not exists public.follows (
  id           bigint generated by default as identity not null,
  follower_id  bigint not null,
  following_id bigint not null,
  created_at   timestamptz default now() not null
);

create table if not exists public.blocks (
  id         bigint generated by default as identity not null,
  blocker_id bigint not null,
  blocked_id bigint not null,
  created_at timestamptz default now() not null
);

create table if not exists public.bookmarks (
  id         bigint generated by default as identity not null,
  user_id    bigint not null,
  post_id    bigint not null,
  created_at timestamptz default now() not null
);

create table if not exists public.hashtags (
  id  bigint generated by default as identity not null,
  tag text not null
);

create table if not exists public.post_hashtags (
  post_id    bigint not null,
  hashtag_id bigint not null
);

create table if not exists public.stories (
  id         bigint generated by default as identity not null,
  user_id    bigint not null,
  media_url  text not null,
  media_type text not null,
  created_at timestamptz default now() not null,
  expires_at timestamptz default (now() + '24:00:00'::interval) not null
);

create table if not exists public.conversations (
  id              bigint generated by default as identity not null,
  user1_id        bigint not null,
  user2_id        bigint not null,
  last_message_at timestamptz default now() not null,
  created_at      timestamptz default now() not null
);

create table if not exists public.messages (
  id              bigint generated by default as identity not null,
  conversation_id bigint not null,
  sender_id       bigint not null,
  content         text not null,
  is_read         boolean default false not null,
  created_at      timestamptz default now() not null
);

create table if not exists public.notifications (
  id         bigint generated by default as identity not null,
  user_id    bigint not null,
  actor_id   bigint not null,
  type       text not null,
  post_id    bigint,
  comment_id bigint,
  is_read    boolean default false not null,
  created_at timestamptz default now() not null
);

create table if not exists public.reports (
  id          bigint generated by default as identity not null,
  reporter_id bigint not null,
  target_type text not null,
  target_id   bigint not null,
  reason      text not null,
  note        text,
  status      text default 'open'::text not null,
  created_at  timestamptz default now() not null
);

create table if not exists public.deleted_media (
  id                  bigint generated by default as identity not null,
  original_id         bigint,
  user_id             bigint,
  caption             text,
  media_type          text,
  original_media_url  text,
  archive_path        text,
  original_created_at timestamptz,
  deleted_at          timestamptz default now() not null
);

-- ── Eşleştirme (/eslesme) ──
create table if not exists public.swipes (
  id         bigint generated by default as identity not null,
  swiper_id  bigint not null,
  target_id  bigint not null,
  direction  text not null,
  created_at timestamptz default now() not null
);

create table if not exists public.matches (
  id              bigint generated by default as identity not null,
  user1_id        bigint not null,
  user2_id        bigint not null,
  conversation_id bigint,
  created_at      timestamptz default now() not null
);

-- ── Makale sosyal ──
create table if not exists public.article_comments (
  id           bigint generated by default as identity not null,
  article_slug text not null,
  user_id      bigint not null,
  content      text not null,
  created_at   timestamptz default now() not null
);

create table if not exists public.article_saves (
  user_id      bigint not null,
  article_slug text not null,
  created_at   timestamptz default now() not null
);

create table if not exists public.article_poll_votes (
  poll_key   text not null,
  voter_hash text not null,
  choice     text not null,
  user_id    bigint,
  created_at timestamptz default now() not null
);

create table if not exists public.user_articles (
  id            bigint generated by default as identity not null,
  user_id       bigint not null,
  slug          text not null,
  title         text not null,
  summary       text default ''::text not null,
  cover_url     text,
  category      text,
  doc           jsonb default '[]'::jsonb not null,
  sources       jsonb default '[]'::jsonb not null,
  status        text default 'pending'::text not null,
  reject_reason text,
  view_count    bigint default 0 not null,
  created_at    timestamptz default now() not null,
  updated_at    timestamptz default now() not null,
  published_at  timestamptz
);

-- ── Bilgi kartı + günün sorusu ──
create table if not exists public.did_you_know (
  id           bigint generated by default as identity not null,
  user_id      bigint,
  title        text not null,
  body         text not null,
  source_url   text,
  source_label text,
  article_slug text,
  image_url    text,
  active       boolean default true not null,
  created_at   timestamptz default now() not null
);

create table if not exists public.quiz_questions (
  id            bigint generated by default as identity not null,
  question      text not null,
  options       jsonb not null,
  correct_index integer not null,
  explanation   text,
  article_slug  text,
  active        boolean default true not null,
  created_at    timestamptz default now() not null
);

create table if not exists public.daily_answers (
  user_id        bigint not null,
  answer_date    date not null,
  question_id    bigint not null,
  selected_index integer not null,
  is_correct     boolean not null,
  created_at     timestamptz default now() not null
);

create table if not exists public.user_progress (
  user_id          bigint not null,
  xp               integer default 0 not null,
  current_streak   integer default 0 not null,
  longest_streak   integer default 0 not null,
  last_answer_date date,
  total_correct    integer default 0 not null,
  total_answered   integer default 0 not null,
  updated_at       timestamptz default now() not null
);

create table if not exists public.user_badges (
  user_id   bigint not null,
  badge_key text not null,
  earned_at timestamptz default now() not null
);

-- ── İstatistik ──
create table if not exists public.login_events (
  id           bigint generated by default as identity not null,
  user_id      bigint not null,
  method       text default 'password'::text not null,
  country_code text,
  country_name text,
  city         text,
  created_at   timestamptz default now() not null
);

create table if not exists public.page_views (
  id           bigint generated by default as identity not null,
  path         text not null,
  country_code text,
  country_name text,
  visitor_hash text,
  created_at   timestamptz default now() not null
);

-- ── Müzik ──
create table if not exists public.spotify_playlists (
  id          bigint generated by default as identity not null,
  user_id     bigint not null,
  playlist_id text not null,
  title       text default ''::text not null,
  created_at  timestamptz default now() not null
);

create table if not exists public.youtube_items (
  id         bigint generated by default as identity not null,
  user_id    bigint not null,
  item_type  text not null,
  item_id    text not null,
  title      text default ''::text not null,
  created_at timestamptz default now() not null
);

create table if not exists public.game_scores (
  id          bigint generated by default as identity not null,
  player_name text not null,
  score       integer not null,
  created_at  timestamptz default now()
);


-- ═══════════════════════════════════════════════════════════════════════════
-- 2 · KISITLAR
-- (UNIQUE ve PRIMARY KEY kısıtları arkalarındaki index'i KENDİLERİ yaratır;
--  o yüzden 3. bölümde tekrar edilmezler.)
-- ═══════════════════════════════════════════════════════════════════════════

alter table public.users
  add constraint users_pkey primary key (id),
  add constraint users_username_key unique (username),
  add constraint users_auth_id_fkey foreign key (auth_id) references auth.users(id) on delete cascade,
  add constraint users_dm_privacy_check      check (dm_privacy      = any (array['everyone'::text, 'followers'::text, 'none'::text])),
  add constraint users_comment_privacy_check check (comment_privacy = any (array['everyone'::text, 'followers'::text, 'none'::text])),
  add constraint users_gender_check          check (gender          = any (array[''::text, 'erkek'::text, 'kadin'::text, 'diger'::text]));

alter table public.quick_facts
  add constraint quick_facts_pkey primary key (id),
  add constraint quick_facts_user_id_fkey foreign key (user_id) references users(id) on delete cascade,
  add constraint quick_facts_media_type_check check (media_type = any (array['image'::text, 'video'::text]));

alter table public.posts
  add constraint posts_pkey primary key (id),
  add constraint posts_user_id_fkey foreign key (user_id) references users(id) on delete cascade;

alter table public.comments
  add constraint comments_pkey primary key (id),
  add constraint comments_post_id_fkey   foreign key (post_id)   references quick_facts(id) on delete cascade,
  add constraint comments_user_id_fkey   foreign key (user_id)   references users(id)       on delete cascade,
  add constraint comments_parent_id_fkey foreign key (parent_id) references comments(id)    on delete cascade,
  add constraint comments_content_check  check (char_length(content) >= 1 and char_length(content) <= 300);

alter table public.fact_likes
  add constraint fact_likes_pkey primary key (user_id, fact_id),
  add constraint fact_likes_user_id_fkey foreign key (user_id) references users(id)       on delete cascade,
  add constraint fact_likes_fact_id_fkey foreign key (fact_id) references quick_facts(id) on delete cascade;

alter table public.post_likes
  add constraint post_likes_pkey primary key (user_id, post_id),
  add constraint post_likes_user_id_fkey foreign key (user_id) references users(id) on delete cascade,
  add constraint post_likes_post_id_fkey foreign key (post_id) references posts(id) on delete cascade;

alter table public.fact_reposts
  add constraint fact_reposts_pkey primary key (user_id, fact_id),
  add constraint fact_reposts_user_id_fkey foreign key (user_id) references users(id)       on delete cascade,
  add constraint fact_reposts_fact_id_fkey foreign key (fact_id) references quick_facts(id) on delete cascade;

alter table public.reposts
  add constraint reposts_pkey primary key (user_id, post_id),
  add constraint reposts_user_id_fkey foreign key (user_id) references users(id) on delete cascade,
  add constraint reposts_post_id_fkey foreign key (post_id) references posts(id) on delete cascade;

alter table public.follows
  add constraint follows_pkey primary key (id),
  add constraint follows_follower_id_following_id_key unique (follower_id, following_id),
  add constraint follows_follower_id_fkey  foreign key (follower_id)  references users(id) on delete cascade,
  add constraint follows_following_id_fkey foreign key (following_id) references users(id) on delete cascade,
  add constraint follows_no_self check (follower_id <> following_id) not valid;

alter table public.blocks
  add constraint blocks_pkey primary key (id),
  add constraint blocks_blocker_id_blocked_id_key unique (blocker_id, blocked_id),
  add constraint blocks_blocker_id_fkey foreign key (blocker_id) references users(id) on delete cascade,
  add constraint blocks_blocked_id_fkey foreign key (blocked_id) references users(id) on delete cascade,
  add constraint blocks_check check (blocker_id <> blocked_id);

alter table public.bookmarks
  add constraint bookmarks_pkey primary key (id),
  add constraint bookmarks_user_id_post_id_key unique (user_id, post_id),
  add constraint bookmarks_user_id_fkey foreign key (user_id) references users(id)       on delete cascade,
  add constraint bookmarks_post_id_fkey foreign key (post_id) references quick_facts(id) on delete cascade;

alter table public.hashtags
  add constraint hashtags_pkey primary key (id),
  add constraint hashtags_tag_key unique (tag);

alter table public.post_hashtags
  add constraint post_hashtags_pkey primary key (post_id, hashtag_id),
  add constraint post_hashtags_post_id_fkey    foreign key (post_id)    references quick_facts(id) on delete cascade,
  add constraint post_hashtags_hashtag_id_fkey foreign key (hashtag_id) references hashtags(id)    on delete cascade;

alter table public.stories
  add constraint stories_pkey primary key (id),
  add constraint stories_user_id_fkey foreign key (user_id) references users(id) on delete cascade,
  add constraint stories_media_type_check check (media_type = any (array['image'::text, 'video'::text]));

alter table public.conversations
  add constraint conversations_pkey primary key (id),
  add constraint conversations_user1_id_user2_id_key unique (user1_id, user2_id),
  add constraint conversations_user1_id_fkey foreign key (user1_id) references users(id) on delete cascade,
  add constraint conversations_user2_id_fkey foreign key (user2_id) references users(id) on delete cascade,
  -- user1_id < user2_id: aynı iki kişi için TEK sohbet satırı olsun diye sıralama
  -- dayatılıyor; yukarıdaki unique kısıtla birlikte çift sohbeti imkânsız kılar.
  add constraint conversations_ordered check (user1_id < user2_id);

alter table public.messages
  add constraint messages_pkey primary key (id),
  add constraint messages_conversation_id_fkey foreign key (conversation_id) references conversations(id) on delete cascade,
  add constraint messages_sender_id_fkey       foreign key (sender_id)       references users(id)         on delete cascade,
  add constraint messages_content_check check (char_length(content) >= 1 and char_length(content) <= 1000);

alter table public.notifications
  add constraint notifications_pkey primary key (id),
  add constraint notifications_user_id_fkey    foreign key (user_id)    references users(id)       on delete cascade,
  add constraint notifications_actor_id_fkey   foreign key (actor_id)   references users(id)       on delete cascade,
  add constraint notifications_post_id_fkey    foreign key (post_id)    references quick_facts(id) on delete cascade,
  add constraint notifications_comment_id_fkey foreign key (comment_id) references comments(id)    on delete cascade,
  add constraint notifications_type_check check (type = any (array['follow'::text, 'comment'::text, 'like'::text, 'mention'::text]));

alter table public.reports
  add constraint reports_pkey primary key (id),
  add constraint reports_reporter_id_fkey foreign key (reporter_id) references users(id) on delete cascade,
  add constraint reports_status_check      check (status      = any (array['open'::text, 'reviewed'::text, 'dismissed'::text])),
  add constraint reports_target_type_check check (target_type = any (array['post'::text, 'comment'::text, 'user'::text, 'article'::text, 'article_comment'::text]));
-- NOT: reports.target_id POLİMORFİK (post/comment/user/article'a işaret edebilir)
-- → FK YOK, olamaz da. Yetim 'open' şikayetler: sql/audit-2026-07-18.sql Bölüm 5.

alter table public.deleted_media
  add constraint deleted_media_pkey primary key (id);
-- NOT: user_id/original_id'de FK YOK — bilinçli: arşiv kaydı, kaynak silinince kalmalı.

alter table public.swipes
  add constraint swipes_pkey primary key (id),
  add constraint swipes_swiper_id_target_id_key unique (swiper_id, target_id),
  add constraint swipes_swiper_id_fkey foreign key (swiper_id) references users(id) on delete cascade,
  add constraint swipes_target_id_fkey foreign key (target_id) references users(id) on delete cascade,
  add constraint swipes_direction_check check (direction = any (array['like'::text, 'pass'::text]));

alter table public.matches
  add constraint matches_pkey primary key (id),
  add constraint matches_user1_id_user2_id_key unique (user1_id, user2_id),
  add constraint matches_user1_id_fkey        foreign key (user1_id)        references users(id)         on delete cascade,
  add constraint matches_user2_id_fkey        foreign key (user2_id)        references users(id)         on delete cascade,
  add constraint matches_conversation_id_fkey foreign key (conversation_id) references conversations(id) on delete set null;

alter table public.article_comments
  add constraint article_comments_pkey primary key (id),
  add constraint article_comments_user_id_fkey foreign key (user_id) references users(id) on delete cascade;

alter table public.article_saves
  add constraint article_saves_pkey primary key (user_id, article_slug),
  add constraint article_saves_user_id_fkey foreign key (user_id) references users(id) on delete cascade;

alter table public.article_poll_votes
  add constraint article_poll_votes_pkey primary key (poll_key, voter_hash),
  -- SET NULL: hesap silinse de anonim oy sayımı bozulmasın.
  add constraint article_poll_votes_user_id_fkey foreign key (user_id) references users(id) on delete set null;

alter table public.user_articles
  add constraint user_articles_pkey primary key (id),
  add constraint user_articles_slug_key unique (slug),
  add constraint user_articles_user_id_fkey foreign key (user_id) references users(id) on delete cascade,
  add constraint user_articles_status_check check (status = any (array['pending'::text, 'approved'::text, 'rejected'::text]));

alter table public.did_you_know
  add constraint did_you_know_pkey primary key (id),
  add constraint did_you_know_user_id_fkey foreign key (user_id) references users(id) on delete set null;

alter table public.quiz_questions
  add constraint quiz_questions_pkey primary key (id);

alter table public.daily_answers
  add constraint daily_answers_pkey primary key (user_id, answer_date),
  add constraint daily_answers_user_id_fkey     foreign key (user_id)     references users(id) on delete cascade,
  -- DİKKAT: on delete YOK (NO ACTION) → cevabı olan bir quiz sorusu SİLİNEMEZ.
  add constraint daily_answers_question_id_fkey foreign key (question_id) references quiz_questions(id);

alter table public.user_progress
  add constraint user_progress_pkey primary key (user_id),
  add constraint user_progress_user_id_fkey foreign key (user_id) references users(id) on delete cascade;

alter table public.user_badges
  add constraint user_badges_pkey primary key (user_id, badge_key),
  add constraint user_badges_user_id_fkey foreign key (user_id) references users(id) on delete cascade;

alter table public.login_events
  add constraint login_events_pkey primary key (id),
  add constraint login_events_user_id_fkey foreign key (user_id) references users(id) on delete cascade;

alter table public.page_views
  add constraint page_views_pkey primary key (id);
-- NOT: page_views'ta user FK YOK — çerezsiz/anonim ölçüm, kişiye bağlanmaz (bilinçli).

alter table public.spotify_playlists
  add constraint spotify_playlists_pkey primary key (id),
  add constraint spotify_playlists_user_id_playlist_id_key unique (user_id, playlist_id),
  add constraint spotify_playlists_user_id_fkey foreign key (user_id) references users(id) on delete cascade;

alter table public.youtube_items
  add constraint youtube_items_pkey primary key (id),
  add constraint youtube_items_user_id_item_type_item_id_key unique (user_id, item_type, item_id),
  add constraint youtube_items_user_id_fkey foreign key (user_id) references users(id) on delete cascade,
  add constraint youtube_items_item_type_check check (item_type = any (array['video'::text, 'playlist'::text]));

alter table public.game_scores
  add constraint game_scores_pkey primary key (id);


-- ═══════════════════════════════════════════════════════════════════════════
-- 3 · INDEX'LER (kısıtların yarattıkları hariç)
--
-- ⚠️ Bu liste canlıdaki hâli AYNEN yansıtır ve içinde MÜKERRER index'ler
-- vardır (ör. idx_fact_likes_user, PK'nın birebir kopyası; uq_follows_pair,
-- follows_follower_id_following_id_key'in kopyası).
-- Temizlik: sql/cleanup-redundant-indexes.sql — çalıştırıldıktan sonra bu
-- bölüm de güncellenmeli.
-- ═══════════════════════════════════════════════════════════════════════════

create unique index if not exists users_username_lower_idx on public.users (lower(username));
create index if not exists idx_users_auth_id    on public.users (auth_id);
create index if not exists idx_users_username   on public.users (username);
create index if not exists idx_users_created_at on public.users (created_at desc);
create index if not exists idx_users_last_seen  on public.users (last_seen_at desc);

create index if not exists idx_quick_facts_created on public.quick_facts (created_at desc, id desc);
create index if not exists idx_quick_facts_user    on public.quick_facts (user_id, created_at desc);
create index if not exists idx_posts_created       on public.posts (created_at desc);

create index if not exists idx_comments_post         on public.comments (post_id);
create index if not exists idx_comments_user         on public.comments (user_id);
create index if not exists idx_comments_parent       on public.comments (parent_id);
create index if not exists idx_comments_user_created on public.comments (user_id, created_at desc);

create index if not exists idx_fact_likes_user   on public.fact_likes (user_id, fact_id);
create index if not exists idx_post_likes_user   on public.post_likes (user_id, post_id);
create index if not exists idx_fact_reposts_user on public.fact_reposts (user_id, fact_id);
create index if not exists fact_reposts_user_idx on public.fact_reposts (user_id, created_at desc);
create index if not exists idx_reposts_user      on public.reposts (user_id);
create index if not exists idx_reposts_post      on public.reposts (post_id);

create index if not exists idx_follows_follower           on public.follows (follower_id);
create index if not exists idx_follows_following          on public.follows (following_id);
create index if not exists idx_follows_follower_following on public.follows (follower_id, following_id);
create unique index if not exists uq_follows_pair         on public.follows (follower_id, following_id);

create index if not exists idx_blocks_blocker on public.blocks (blocker_id);
create index if not exists idx_blocks_blocked on public.blocks (blocked_id);

create index if not exists idx_bookmarks_user            on public.bookmarks (user_id);
create index if not exists idx_bookmarks_post            on public.bookmarks (post_id);
create index if not exists idx_bookmarks_user_post       on public.bookmarks (user_id, post_id);
create index if not exists idx_bookmarks_user_created    on public.bookmarks (user_id, created_at desc);
create unique index if not exists uq_bookmarks_user_post on public.bookmarks (user_id, post_id);

create index if not exists idx_post_hashtags_post    on public.post_hashtags (post_id);
create index if not exists idx_post_hashtags_hashtag on public.post_hashtags (hashtag_id);

create index if not exists idx_stories_user            on public.stories (user_id, expires_at);
create index if not exists idx_stories_expires         on public.stories (expires_at);
create index if not exists idx_stories_active          on public.stories (expires_at desc);
create index if not exists idx_stories_created         on public.stories (created_at desc);
create index if not exists idx_stories_expires_created on public.stories (expires_at, created_at desc);

create index if not exists idx_conv_user1    on public.conversations (user1_id);
create index if not exists idx_conv_user2    on public.conversations (user2_id);
create index if not exists idx_conv_u1       on public.conversations (user1_id, last_message_at desc);
create index if not exists idx_conv_u2       on public.conversations (user2_id, last_message_at desc);
create index if not exists idx_conv_last_msg on public.conversations (last_message_at desc);

create index if not exists idx_msg_conv         on public.messages (conversation_id, created_at);
create index if not exists idx_msg_conv_created on public.messages (conversation_id, created_at desc);
create index if not exists idx_msg_conv_unread  on public.messages (conversation_id, is_read);
create index if not exists idx_msg_unread       on public.messages (conversation_id, is_read) where (not is_read);

-- idx_notif_like_dedup: PostgREST'in `on_conflict` çıkarımı KISMİ index'i
-- KULLANAMAZ (eşleşmesi için `WHERE type='like'` koşulunu üretmesi gerekirdi,
-- üretmiyor). Bu yüzden eski upsert her seferinde 42P10 ile düşüyor ve beğeni
-- bildirimleri sessizce kayboluyordu. lib/notify.ts artık açık
-- "var mı? yoksa ekle" yapıyor; bu index yalnızca yarış koruması.
create unique index if not exists idx_notif_like_dedup  on public.notifications (user_id, actor_id, post_id) where (type = 'like'::text);
create unique index if not exists uq_notifications_like on public.notifications (user_id, actor_id, post_id) where (type = 'like'::text);
create index if not exists idx_notif_user_created on public.notifications (user_id, created_at desc);
create index if not exists idx_notif_user_unread  on public.notifications (user_id, is_read, created_at desc);

create index if not exists idx_reports_open       on public.reports (status, created_at desc);
create index if not exists idx_reports_reporter   on public.reports (reporter_id, created_at desc);
create unique index if not exists uq_reports_once on public.reports (reporter_id, target_type, target_id);

create index if not exists idx_swipes_swiper      on public.swipes (swiper_id);
create index if not exists idx_swipes_target_like on public.swipes (target_id, direction);
create index if not exists idx_matches_user1      on public.matches (user1_id, created_at desc);
create index if not exists idx_matches_user2      on public.matches (user2_id, created_at desc);

create index if not exists idx_article_comments_slug_created  on public.article_comments (article_slug, created_at);
create index if not exists idx_article_saves_user_created     on public.article_saves (user_id, created_at desc);
create index if not exists idx_article_poll_votes_key_choice  on public.article_poll_votes (poll_key, choice);
create index if not exists idx_user_articles_status_published on public.user_articles (status, published_at desc);
create index if not exists idx_user_articles_user_created     on public.user_articles (user_id, created_at desc);

create index if not exists idx_dyk_active_created on public.did_you_know (active, created_at desc);
create index if not exists idx_quiz_active        on public.quiz_questions (active, id);

create index if not exists idx_login_events_user    on public.login_events (user_id, created_at desc);
create index if not exists idx_login_events_created on public.login_events (created_at desc);
create index if not exists idx_login_events_country on public.login_events (country_code);

create index if not exists idx_page_views_created      on public.page_views (created_at desc);
create index if not exists idx_page_views_created_hash on public.page_views (created_at desc, visitor_hash);
create index if not exists idx_page_views_hash         on public.page_views (visitor_hash, created_at desc);
create index if not exists idx_page_views_path         on public.page_views (path);
create index if not exists idx_page_views_country      on public.page_views (country_code);

create index if not exists idx_spotify_playlists_user on public.spotify_playlists (user_id);
create index if not exists idx_spotify_playlists_time on public.spotify_playlists (created_at desc);
create index if not exists idx_spotify_created        on public.spotify_playlists (created_at desc);
create index if not exists idx_youtube_items_user     on public.youtube_items (user_id);
create index if not exists idx_youtube_items_time     on public.youtube_items (created_at desc);
create index if not exists idx_youtube_created        on public.youtube_items (created_at desc);


-- ═══════════════════════════════════════════════════════════════════════════
-- 4 · RLS
--
-- DESEN: TÜM tablolarda RLS AÇIK ve HİÇBİRİNDE politika YOK. Bu bilinçli:
-- erişimin tamamı sunucu tarafındaki service-role client üzerinden geçer
-- (lib/supabase/server.ts). Politika olmaması = anon ve authenticated
-- rollerinin hiçbir satırı görememesi.
--
-- 2026-07-18'de bağımsız DOĞRULANDI: anon anahtarla `messages` 0 satır döndü,
-- service-role ile 10 satır. Koruma gerçekten işliyor.
--
-- SONUCU: gizlilik kuralları (is_private, engelleme) DB'de DEĞİL, UYGULAMA
-- katmanında uygulanır → her yeni küresel listeleme yüzeyinde ELLE
-- filtrelenmeleri ŞART. Bu unutulduğu için /api/feed'in facts dalından gizli
-- hesaplar sızmıştı (2026-07-18'de düzeltildi).
-- ═══════════════════════════════════════════════════════════════════════════

alter table public.users              enable row level security;
alter table public.quick_facts        enable row level security;
alter table public.posts              enable row level security;
alter table public.comments           enable row level security;
alter table public.fact_likes         enable row level security;
alter table public.post_likes         enable row level security;
alter table public.fact_reposts       enable row level security;
alter table public.reposts            enable row level security;
alter table public.follows            enable row level security;
alter table public.blocks             enable row level security;
alter table public.bookmarks          enable row level security;
alter table public.hashtags           enable row level security;
alter table public.post_hashtags      enable row level security;
alter table public.stories            enable row level security;
alter table public.conversations      enable row level security;
alter table public.messages           enable row level security;
alter table public.notifications      enable row level security;
alter table public.reports            enable row level security;
alter table public.deleted_media      enable row level security;
alter table public.swipes             enable row level security;
alter table public.matches            enable row level security;
alter table public.article_comments   enable row level security;
alter table public.article_saves      enable row level security;
alter table public.article_poll_votes enable row level security;
alter table public.user_articles      enable row level security;
alter table public.did_you_know       enable row level security;
alter table public.quiz_questions     enable row level security;
alter table public.daily_answers      enable row level security;
alter table public.user_progress      enable row level security;
alter table public.user_badges        enable row level security;
alter table public.login_events       enable row level security;
alter table public.page_views         enable row level security;
alter table public.spotify_playlists  enable row level security;
alter table public.youtube_items      enable row level security;
alter table public.game_scores        enable row level security;


-- ═══════════════════════════════════════════════════════════════════════════
-- 5 · FONKSİYONLAR ve TRIGGER'LAR
--
-- Bu bölüm KASITLI BOŞ — tanımlar ayrı dosyalarda, tek doğruluk kaynağı olsun:
--   · sql/functions-toggles.sql          → toggle_fact_like, toggle_post_like,
--                                           toggle_post_repost
--   · sql/features-login-tracking.sql    → login_dashboard
--   · sql/features-visitor-tracking.sql  → traffic_dashboard
--   · sql/fix-handle-new-user.sql        → handle_new_user
--
-- Kaynağı HÂLÂ SADECE canlıda olan üç fonksiyon:
--   · increment_fact_likes(bigint)  — toggle_fact_like tarafından değiştirildi
--   · increment_post_likes(bigint)  — toggle_post_like tarafından değiştirildi
--     (ikisi de artık çağrılmıyor görünüyor; silmeden önce grep ile doğrula)
--   · app_delete_user(text)         — yönetimsel: kullanıcıyı public.users +
--                                      auth.users'tan siler
--
-- TRIGGER — `public` DIŞINDA olduğu için `--schema public` dump'ı KAÇIRIRDI:
--   create trigger on_auth_user_created
--     after insert on auth.users
--     for each row execute function public.handle_new_user();
--
-- (Diğer trigger'lar Supabase'in kendi altyapısına ait: realtime.subscription,
--  storage.buckets, storage.objects — bunlar bizim değil, dökülmedi.)
-- ═══════════════════════════════════════════════════════════════════════════
